name: zhongbiao

on:
  workflow_dispatch:  # This allows manual trigger from the GitHub UI.
    inputs:
        url:
          description: 'domain url'
          required: false
          type: string

jobs:
  google_search:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install required Python dependencies
      run: |
        pip install DataRecorder aiohttp pandas DrissionPage python-dotenv markitdown

    - name: Run the Google search parser script
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}    
      run: |
        python zhongbiao.py \
          --url ${{ github.event.inputs.url }}

    - name: Commit the results to the repository if there's a change
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        git diff --quiet || git commit -m "Add new Google search results"
        # git pull --rebase
        git push
